name: fake

on:
  schedule:
    - cron:  '0 4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Run script
      run: python fake.py

    - name: Push change commit
      run: |
        git config user.name liyangxia
        git config user.email 126838514+liyangxia@users.noreply.github.com
        git add -A
        git commit -m "$(date +%Y%m%d%H%M)"
        git push -u origin master
